### ISSUE TITLE
[tag 3.0.0] Error  call ingo#err#Clear()

### ISSUE THREAD

**Issue by Kris2k** [inkarkat/vim-mark#5] opened 2018-03-22 08:14 UTC
Hi I used tag 3.0.0 and I got error
```
Error detected while processing function mark#MarkCurrentWord[13]..mark#DoMark:
line    1:
E117: Unknown function: ingo#err#Clear
```
I have impression that functions there by accident.

**Comment by inkarkat** [comment] 2018-03-22 08:46
You also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-mark#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues.

(Duplicate of #1.)

**Closed by inkarkat** 2018-03-22 08:46 UTC
