### ISSUE TITLE
Error when marking with "<Leader>m"

### ISSUE THREAD

**Issue by guru245** [inkarkat/vim-mark#8] opened 2018-06-24 10:31 UTC
Hello,

When marking with "<Leader>m" on mark-3.0.0, I get the following error.
```
Error detected while processing function mark#MarkCurrentWord[13]..mark#DoMark:line    1:
E117: Unknown function: ingo#err#Clear
mark-1/\<config\>
Press ENTER or type command to continue
```
Marking still works though.

More details comes below.
- With mark-2.8.5, downloaded from vim.org, there is no issue. 
- With mark-3.0.0, downloaded from Github, this issue happens.

If you have any problem to reproduce the issue, let me know.

Regards,

Sangho

**Comment by inkarkat** [comment] 2018-06-24 17:51
Duplicate of #1 and #5.

Starting with version 3.0.0, you also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-mark#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues.

**Closed by inkarkat** 2018-06-24 17:51 UTC
